fix: "copilot_prepare_and_edit_settings" not working
PermissionError: [WinError 5] 存取被拒。: '${packages}'

Because "${packages}" is not expanded into exact path.

Signed-off-by: Jack Cherng <jfcherng@gmail.com>